# 1. HTTP to HTTPS Redirect Block
server {
    listen 80;
    server_name 34.234.138.97.nip.io;
    
    return 301 https://$host$request_uri;
}

# 2. Primary Secure HTTPS Block
server {
    listen 443 ssl;
    server_name 34.234.138.97.nip.io;

    # SSL Certificates
    ssl_certificate /etc/letsencrypt/live/34.234.138.97.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/34.234.138.97.nip.io/privkey.pem;

    # frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # backend
    location /api/ {
        proxy_pass http://backend:8080; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; # Tells Go this is HTTPS
    }

    # websocket
    location /ws/ {
        proxy_pass http://backend:8080;
        
        # Mandatory WebSocket Upgrade Headers
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme; # Tells Go this is WSS
        
        # Keep WebRTC alive during long video calls
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # minio
    location ~ ^/(user-avatars|galleries|covers)/ {
        client_max_body_size 20M; 
        
        # 'minio' must match the service name in docker-compose.yml
        # 9000 is the standard MinIO API port (9001 is for the console)
        proxy_pass http://minio:9000; 
        
        # MinIO strictly requires the original host header
        proxy_set_header Host $http_host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # MinIO CORS (Prevents canvas/image manipulation blocking in React)
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
    }
    
    # static assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4|webm)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
