name: containerized-integration-workflows
run-name: continuous integration
on:
    push:
        branches: [main, release]
    pull_request:
        branches: [main]

concurrency:
    group: ${{github.workflow}}-${{github.ref}}

jobs:
    evaluate-target-environment:
        runs-on: ubuntu-latest
        steps:
            - name: output environment variable
              id: verbose_log
              run: |
                ENV_TO_RUN="dev"
                echo "Currently take code from $GITHUB_REF, with env $ENV_TO_RUN"
                echo "target_env=$ENV_TO_RUN" >> $GITHUB_OUTPUT
        outputs:
            env_value: ${{steps.verbose_log.outputs.target_env}}
    
    build-and-push-backend:
        runs-on: ubuntu-latest
        needs: evaluate-target-environment

        # check env
        environment: ${{needs.evaluate-target-environment.outputs.env_value}}

        # working dir
        defaults:
            run:
                working-directory: ./lokask-backend/backend

        # token permission
        permissions:
            id-token: write
            contents: read
        steps:
            - name: git checkout the repo
              uses: actions/checkout@v4

            - name: setup golang
              uses: actions/setup-go@v5
              with:
                go-version: '1.26'
                cache-dependency-path: lokask-backend/backend/go.sum

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: login into DockerHub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
            
            - name: build and tag image
              uses: docker/build-push-action@v5
              with:
                context: ./lokask-backend/backend
                file: ./lokask-backend/backend/Dockerfile
                push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
                tags: |
                    ${{ vars.DOCKER_HUB_USERNAME }}/lokask-repository:backend-${{ github.sha }}
                    ${{ vars.DOCKER_HUB_USERNAME }}/lokask-repository:backend-latest
                cache-from: type=registry,ref=${{ vars.DOCKER_HUB_USERNAME }}/lokask-repository:buildcache
                cache-to: type=registry,ref=${{ vars.DOCKER_HUB_USERNAME }}/lokask-repository:buildcache,mode=max
    
    build-and-push-frontend:
        runs-on: ubuntu-latest
        needs: evaluate-target-environment
        environment: ${{needs.evaluate-target-environment.outputs.env_value}}

        defaults:
            run:
                working-directory: ./lokask-frontend

        permissions:
            id-token: write
            contents: read
        
        steps:
            - name: git checkout repo
              uses: actions/checkout@v4
            - name: setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: lokask-frontend/package-lock.json
            
            - name: install, lint and verification
              run: |
                npm ci
                npx tsc --noEmit
                npm run build --if-present

            - name: setup docker build
              uses: docker/setup-buildx-action@v3

            - name: login into DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
                
            - name: build and tag image
              uses: docker/build-push-action@v5
              with:
                context: ./lokask-frontend
                file: ./lokask-frontend/Dockerfile
                push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
                tags: |
                    ${{ vars.DOCKER_HUB_USERNAME }}/lokask-repository:frontend-${{ github.sha }}
                    ${{ vars.DOCKER_HUB_USERNAME }}/lokask-repository:frontend-latest
                cache-from: type=registry,ref=${{ vars.DOCKER_HUB_USERNAME }}/lokask-repository:frontend-buildcache
                cache-to: type=registry,ref=${{ vars.DOCKER_HUB_USERNAME }}/lokask-repository:frontend-buildcache,mode=max
    
    deploy-to-server:
        runs-on: ubuntu-latest
        needs: [build-and-push-backend, build-and-push-frontend, evaluate-target-environment]
        if: >
            github.ref == 'refs/heads/main' &&
            contains(github.event.head_commit.message, 'release')
        
        environment: ${{needs.evaluate-target-environment.outputs.env_value}}
        
        steps:
            - name: configure SSH
              run: |
                mkdir -p ~/.ssh
                chmod 700 ~/.ssh

                echo "${{ secrets.SSH_HOST_KEY }}" > ~/.ssh/deploy_key
                chmod 600 ~/.ssh/deploy_key

                ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts

            - name: depkoy via SSH
              env:
                DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
                DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
              run: |
                ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_HOST_USER }}@${{ secrets.SSH_HOST_IP }} << EOF
                    cd /lokask/lokask-backend
                    echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
                    echo "Pulling latest images..."
                    docker compose pull
                    echo "Recreating containers..."
                    docker compose up -d
                    echo "Cleaning up..."
                    docker image prune -f
                    docker logout
                EOF
