name: containerized-integration-workflows
run-name: continuous integration
on:
    push:
        branches: [main, release]
    pull_request:
        branches: [main]

concurrency:
    group: ${{github.workflow}}-${{github.ref}}

jobs:
    evaluate-target-environment:
        if: ${{github.ref == '/refs/heads/main'}}
        runs-on: ubuntu-latest
        steps:
            - name: output environment variable
              id: verbose_log
              run: |
                ENV_TO_RUN="dev"
                echo "Currently take code from $GITHUB_REF, with env $ENV_TO_RUN"
                echo "target_env=$ENV_TO_RUN" >> $GITHUB_OUTPUT
        outputs:
            env_value: ${{steps.verbose_log.outputs.target_env}}
    
    build-and-push-backend:
        runs-on: ubuntu-latest
        needs: evaluate-target-environment

        # check env
        environment: ${{needs.evaluate-target-environment.outputs.env_value}}

        # working dir
        defaults:
            run:
                working-directory: ./lokask-backend/backend

        # token permission
        permissions:
            id-token: write
            contents: read
        steps:
            - name: git checkout the repo
              uses: actions/checkout@v4

            - name: setup golang
              uses: actions/setup-go@v5
              with:
                go-version: '1.26'
                cache-dependency-path: lokask-backend/backend/go.sum
            - name: login into DockerHub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
            
            - name: build and tag image
              uses: docker/build-push-action@v5
              with:
                context: ./lokask-backend/backend
                file: ./lokask-backend/backend/Dockerfile
                push: ${{ github.event_name == 'push' }}
                tags: |
                    ${{ secrets.DOCKERHUB_USERNAME }}/lokask-repository:backend-${{ github.sha }}
                    ${{ secrets.DOCKERHUB_USERNAME }}/lokask-repository:backend-latest
                cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/lokask-repository:buildcache
                cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/lokask-repository:buildcache,mode=max